
version: '3.8'

services:
  nginx:
    image: nginx:stable-alpine3.23-perl
    container_name: Lumo_Nginx
    hostname: nginx
    restart: on-failure
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro # 설정 파일 마운트
      - /usr/share/zoneinfo/Asia/Seoul:/etc/localtime:ro
    depends_on:
      - spring-blue
      - spring-green
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:80 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 2

  spring-blue:
    build: .
    image: jijysun/lumo:lastest
    container_name: Lumo_Blue
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST = {MYSQL_HOST}
      - MYSQL_NAME = {MYSQL_NAME}
      - MYSQL_PASSWORD= {MYSQL_PASSWORD}
      - MYSQL_USERNAME= {MYSQL_USERNAME}
    restart: on-failure

  spring-green:
    build: .
    image: jijysun/lumo:lastest
    container_name: Lumo_Green
    ports:
      - "8080:8081"
    environment:
      - MYSQL_HOST = {MYSQL_HOST}
      - MYSQL_NAME = {MYSQL_NAME}
      - MYSQL_PASSWORD= {MYSQL_PASSWORD}
      - MYSQL_USERNAME= {MYSQL_USERNAME}
    restart: on-failure


# 이후 성능 측정 툴 대비
  prometheus:
    image: prom/prometheus:latest
    container_name: Lumo_Prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command: --config.file=/etc/prometheus/prometheus.yml
    restart: on-failure

  grafana:
    image: grafana/grafana:latest
    container_name: Lumo_Grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    restart: on-failure

volumes:
  grafana_data: # Grafana 데이터 영속성을 위한 볼륨 정의