services:
  Blue:
    build: .
    image: jijysun/lumo:latest
    container_name: Lumo_Blue
    ports:
      - "8081:8080"
    #    depends_on:
    #      - redis
    env_file: .env
    networks:
      - my-network
    restart: on-failure

  Green:
    build: .
    image: jijysun/lumo:latest
    container_name: Lumo_Green
    ports:
      - "8082:8080"
    env_file: .env
    networks:
      - my-network
    restart: on-failure

  #  redis:
  #    image: redis:alpine
  #    container_name: Lumo_Redis
  #    ports:
  #      - "6379:6379"
  #    volumes:
  #      - redis_data:/data
  #    networks:
  #      - lumo-network
  #    restart: on-failure

  # 이후 성능 측정 툴 대비
  prometheus:
    image: prom/prometheus:latest
    container_name: Lumo_Prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - my-network
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: Lumo_Grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=0000
      - GF_USERS_ALLOW_SIGN_UP=false # 회원가입 비활성화
    depends_on:
      - prometheus
    networks:
      - my-network
    restart: always

  loki:
    image: grafana/loki:latest
    container_name: Lumo_Loki
    ports:
      - "3100:3100"
    volumes:
      - ./monitoring/loki/local-config.yaml:/etc/loki/local-config.yaml
    command:
      - -config.file=/etc/loki/local-config.yaml
    networks:
      - my-network
    restart: always

  promtail:
    image: grafana/promtail:latest
    container_name: Lumo_Promtail
    volumes:
      - ./monitoring/promtail/promtail-config.yaml:/etc/promtail/config.yaml
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers:ro # 호스트 로그 경로 추가
    command:
      - -config.file=/etc/promtail/config.yaml
    networks:
      - my-network
    restart: always

volumes:
  grafana_data: # Grafana 데이터 영속성을 위한 볼륨 정의
  prometheus_data:
#  redis_data:

networks:
  my-network:
    driver: bridge