
version: '3.8'

services:
  Blue:
    build: .
    image: jijysun/lumo:latest
    container_name: Lumo_Blue
    ports:
      - "8081:8080"
#    depends_on:
#      - redis
    env_file: .env
    restart: on-failure

  Green:
    build: .
    image: jijysun/lumo:latest
    container_name: Lumo_Green
    ports:
      - "8082:8080"
    env_file: .env
    restart: on-failure

#  redis:
#    image: redis:alpine
#    container_name: Lumo_Redis
#    ports:
#      - "6379:6379"
#    volumes:
#      - redis_data:/data
#    networks:
#      - lumo-network
#    restart: on-failure

# 이후 성능 측정 툴 대비
  prometheus:
    image: prom/prometheus:latest
    container_name: Lumo_Prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command: --config.file=/etc/prometheus/prometheus.yml
    restart: on-failure

  grafana:
    image: grafana/grafana:latest
    container_name: Lumo_Grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    restart: on-failure

volumes:
  grafana_data: # Grafana 데이터 영속성을 위한 볼륨 정의
  prometheus_data:
#  redis_data: