logging:
  level:
    show_sql: DEBUG

spring:
  application:
    name: lumo-backend

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:3306/${MYSQL_NAME}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
  mail:
    host: ${MAIL_SENDER_HOST}
    port: 587
    username: ${MAIL_SENDER_USERNAME}
    password: ${MAIL_SENDER_PASSWORD}

  data:
    redis:
      host: 127.0.0.1
      port: 6379

  sql:
    init:
      mode: never

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus # health + prometheus 엔드포인트 노출
  endpoint:
    health:
      show-details: always # 상세 상태 확인

jwt:
  secret:
    key: ${JWT_SECRET_KEY}