name: Lumo-Deploy
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 레포 체킹
        uses: actions/checkout@v3

      - name: 도커 로그인
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: 도커 빌드 + 이미지 업로드
        run: |
          chmod +x ./gradlew 
          docker build -t ${{secrets.DOCKER_USERNAME}}/lumo .
          docker push ${{secrets.DOCKER_USERNAME}}/lumo

      - name: EC2 작업
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.EC2_HOST}}
          username: ${{secrets.EC2_USERNAME}}
          key: ${{secrets.EC2_PRIVATE_KEY}}
          script: |
            # 합치려고 했으나, workflow 상 연결 오버헤드 발생으로 합쳐서 작성
            # 1. git repo 디렉토리 확인
            if [ -d "Lumo" ]; then
              echo "Git repository already exists. Pulling !!"
              cd Lumo
              sudo git pull origin main
            else
              echo "Git repository not found. Cloning !"
              git clone https://github.com/LUMO-lumo/lumo-backend.git
              cd Lumo
            fi
            
            # 2. env 작성
            echo "MYSQL_HOST=${{secrets.MYSQL_HOST}}" > .env 
            echo "MYSQL_NAME=${{secrets.MYSQL_NAME}}" >> .env
            echo "MYSQL_USERNAME=${{secrets.MYSQL_USERNAME}}" >> .env
            echo "MYSQL_PASSWORD=${{secrets.MYSQL_PASSWORD}}" >> .env
            echo "MAIL_SENDER_HOST=${{secrets.MAIL_SENDER_HOST}}" >> .env
            echo "MAIL_SENDER_USERNAME=${{secrets.MAIL_SENDER_USERNAME}}" >> .env
            echo "MAIL_SENDER_PASSWORD=${{secrets.MAIL_SENDER_PASSWORD}}" >> .env
            echo "REDIS_HOST=${{secrets.REDIS_HOST}}" >> .env
            echo "JWT_SECRET_KEY=${{secrets.JWT_SECRET_KEY}}" >> .env
            
            # 3. 도커 로그인 
            sudo docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
            sudo docker-compose pull
            
            # Blue-Green deploy
            bash /home/ubuntu/nginx/deploy.sh 2>&1 | sudo tee deploy.log