name: Lumo-Deploy
on:
  push:
    branches:
      - main

jobs:
  build-and-push-to-docker:
    runs-on: ubuntu-latest
    steps:
      - name: checking repo...
        uses: actions/checkout@v4

      - uses: actions/checkout@v4
      - name: setting jdk...
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle' # 캐싱

      - name: build with gradle # 배포 전 빌드 테스팅
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test 

      - name: logging in docker...
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: build docker and push image..
        run: |
          chmod +x ./gradlew 
          docker build -t ${{secrets.DOCKER_USERNAME}}/lumo .
          docker push ${{secrets.DOCKER_USERNAME}}/lumo

      - name: copy docker-compose and env...
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.EC2_HOST}}
          username: ${{secrets.EC2_USERNAME}}
          key: ${{secrets.EC2_PRIVATE_KEY}}
          source: "docker-compose.yml, deploy.sh"
          target: "~/lumo"

  ec2-deploy:
    needs: build-and-push-to-docker
    runs-on: ubuntu-latest
    steps:
      - name: working in ec2...
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.EC2_HOST}}
          username: ${{secrets.EC2_USERNAME}}
          key: ${{secrets.EC2_PRIVATE_KEY}}
          script: |
            mkdir -p ~/lumo
            cd ~/lumo
            
            echo "MYSQL_HOST=${{secrets.MYSQL_HOST}}" > .env 
            echo "MYSQL_NAME=${{secrets.MYSQL_NAME}}" >> .env
            echo "MYSQL_PORT=${{secrets.MYSQL_PORT}}" >> .env
            echo "MYSQL_USERNAME=${{secrets.MYSQL_USERNAME}}" >> .env
            echo "MYSQL_PASSWORD=${{secrets.MYSQL_PASSWORD}}" >> .env
            echo "MAIL_SENDER_HOST=${{secrets.MAIL_SENDER_HOST}}" >> .env
            echo "MAIL_SENDER_USERNAME=${{secrets.MAIL_SENDER_USERNAME}}" >> .env
            echo "MAIL_SENDER_PASSWORD=${{secrets.MAIL_SENDER_PASSWORD}}" >> .env
            echo "REDIS_HOST=${{secrets.REDIS_HOST}}" >> .env
            echo "REDIS_PORT=${{secrets.REDIS_PORT}}" >> .env
            echo "JWT_SECRET_KEY=${{secrets.JWT_SECRET_KEY}}" >> .env
            echo "OPENAI_API_KEY=${{secrets.OPENAI_API_KEY}}" >> .env
            
            sudo docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
            sudo docker compose pull
            
            chmod +x deploy.sh
            sudo bash ./deploy.sh 2>&1 | sudo tee deploy.log